default_platform(:ios)

# Configured for Staging builds

platform :ios do
  desc "Submit a new build to TestFlight"
  lane :upload_to_testflight do |options|

    scheme = options[:scheme] || "staging"
    flavor = options[:flavor] || "staging"

    # Ensure correct configuration
    build_configuration = flavor == "prod" ? "Release-prod" : "Release-staging"

    # Build the app
    sh "flutter build ipa --flavor #{flavor} --release"

    # API key path validation
      api_key_path = "./fastlane/AuthKey_#{ENV['APP_STORE_KEY_ID']}.p8"
      unless File.exist?(api_key_path)
        UI.user_error!("API Key not found at #{api_key_path}")
      end

    # Upload to TestFlight
    pilot(
      app_identifier: "com.masterly.flutterbasecodestg",
      api_key: ENV['APP_STORE_API_KEY'],
      api_key_id: ENV['APP_STORE_KEY_ID'],
      issuer_id: ENV['APP_STORE_ISSUER_ID'],
      team_id: ENV['FASTLANE_TEAM_ID'],
      skip_waiting_for_build_processing: false
    )
  end

#  desc "Submit a new build to App Store"
#   lane :upload_to_app_store do |options|
#
#       scheme = options[:scheme] || "Runner"
#       flavor = options[:flavor] || "prod"
#       build_configuration = "Release"
#
#       # Build the app using Flutter
#       sh "flutter build ipa --flavor #{flavor} --release"
#
#       # Upload to App Store
#       deliver(
#         app_identifier: "com.masterly.flutterbasecodestg",
#         api_key_path: "./fastlane/AuthKey_#{ENV['APP_STORE_KEY_ID']}.p8",
#         api_key_id: ENV['APP_STORE_KEY_ID'],
#         issuer_id: ENV['APP_STORE_ISSUER_ID'],
#         team_id: ENV['FASTLANE_TEAM_ID'],
#         skip_metadata: true,
#         skip_screenshots: true,
#         force: true
#       )
#     end
end
