default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :release_beta do
    # Ensure certificates and provisioning profiles are managed
    match(type: "appstore", readonly: false, app_identifier: "com.masterly.flutterbasecodestg", team_id: ENV["BN6UXX7XJP"])

    # Build the app
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "staging", # or "prod" for production
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          "com.masterly.flutterbasecodestg" => "masterly_flutterbasecode_ios_appstore"
        }
      }
    )

    # Upload to TestFlight
    upload_to_testflight
  end
end
