// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9y2R-_1LK51E8QTfjg2EGbPXrb3X90rk',
    appId: '1:813740183088:web:368ec0ef73a7baaba567f5',
    messagingSenderId: '813740183088',
    projectId: 'loanquantum',
    authDomain: 'loanquantum.firebaseapp.com',
    storageBucket: 'loanquantum.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0VPM3UQNkqqs9JEXVGMHTYWueAEDcnXY',
    appId: '1:477121729769:android:4878d69c6711f1bce2cc78',
    messagingSenderId: '477121729769',
    projectId: 'flutter-base-45674',
    storageBucket: 'flutter-base-45674.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5no-fBONdR9rdUkL4oEcb_oxUM1mFZkE',
    appId: '1:477121729769:ios:9ed4e2a1a6e2ff06e2cc78',
    messagingSenderId: '477121729769',
    projectId: 'flutter-base-45674',
    storageBucket: 'flutter-base-45674.firebasestorage.app',
    iosBundleId: 'com.masterly.flutterbase',
  );
}
